# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
    issues: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.1
              with:
                  version: 6.32.6
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  cache-dependency-path: 'common/config/rush/pnpm-lock.yaml'

            # - name: Install dependencies
            #   run: |
            #       node common/scripts/install-run-rush.js change -v
            #       node common/scripts/install-run-rush.js install
            #       node common/scripts/install-run-rush.js build

            - name: Audit not stored
              continue-on-error: true
              run: |
                  cd common/config/rush
                  pnpm audit --ignore-registry-errors

            - name: create string
              run: |
                  cd common/config/rush
                  export JSON_RESPONSE="$(pnpm audit --ignore-registry-errors)"
                  JSON_RESPONSE="${JSON_RESPONSE//'%'/'%25'}"
                  JSON_RESPONSE="${JSON_RESPONSE//$'\n'/'%0A'}"
                  JSON_RESPONSE="${JSON_RESPONSE//$'\r'/'%0D'}"
                  echo "::set-output name=changelog::$(echo "$JSON_RESPONSE")"
              id: my_string
            - name: display string
              run: |
                  echo "The string is: ${{ steps.my_string.outputs.changelog }}"

            - uses: dblock/create-a-github-issue@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  AUDITRES: ${{ steps.my_string.outputs.changelog }}
              with:
                  update_existing: true
                  search_existing: all
            # # Run eslint to check all packages
            # - name: Lint packages
            #   run: node common/scripts/install-run-rush.js lint
            # - name: Run tests
            #   run: node common/scripts/install-run-rush.js test
